from .best_exposure_time import best_exposure_time
from .best_fit_allocation import best_fit_allocation
from .less_allocation import less_distance_allocation
from .random_allocation import random_allocation
from .simple_allocation import simple_allocation